### ISSUE TITLE
Non-torrent downloads

### ISSUE THREAD

**Issue by SmartBoy84** [pedrolemoz/MagicMagnet-Python#22]
I know this would be extremely hard to implement but if you could expand this to other download links that would be epic!

Edit: I realise that this would be hard because with magnet links you just have to search through a page for a magnet:// link but download links have captchas, ad.fly etc but if this could be done it would make an already amazing *tool even better.

*;)

**Comment by david92003** [comment]
There are other programs (I use JDownloader2) for these purposes.

**Comment by pedrolemoz** [comment]
It's actually possible if we can develop a way to bypass adfly and other captchas. The search engine will work similarly in this case
