### ISSUE TITLE
I get no results when searching

### ISSUE THREAD

**Issue by mamk02** [pedrolemoz/MagicMagnet-Python#7]
whenever i try to search for anything, i get no results.

**Comment by pedrolemoz** [comment]
Have you selected a search source? Google sometimes can't find links for you because of DMCA's. Try TPB, 1337x and other sources for you content

**Comment by mamk02** [comment]
Nope, still works pretty bad. When i selecet Google and TPB, and i search for "microsoft office", i get only one result.  Maybe it's because my ISP blocked most of these websites?

**Comment by Vynokris** [comment]
I think selecting all search sources works quite well : I've got 46 results for "microsoft office"

**Comment by pedrolemoz** [comment]
Well, it's your ISP / Country. I'm in Brazil, an that's what I get when searching for Microsoft Office.

![Screenshot_2020-07-13-18-21-26-297_com pedrolemoz magicmagnet](https://user-images.githubusercontent.com/20285104/87355729-3d449780-c537-11ea-9d05-45c5ec2c2e5f.jpg)

Spoiler: this is a mobile version of Magic Magnet, which I'll publish in Google Play Store soon. I'm creating this application with Flutter, so, it will ran on Android, iOS, Mac, Windows, Linux and maybe, Web (I need somewhere to host). It's a lot better than this Python version (it's asynchronous code, and Dart is extremely fast and lightweight compared to Python).
